# all models
./jobs/performance/primer.sh 'churn' 2 1440 'short'
./jobs/performance/primer.sh 'surgical' 2 1440 'short'
./jobs/performance/primer.sh 'vaccine' 2 1440 'short'
./jobs/performance/primer.sh 'amazon' 7 1440 'short'
./jobs/performance/primer.sh 'bank_marketing' 2 1440 'short'
./jobs/performance/primer.sh 'adult' 2 1440 'short'
./jobs/performance/primer.sh 'census' 7 1440 'short'

# single model
./jobs/performance/primer_single.sh 'census' 'lr' 'standard' 1.0 7 1440 'short'
./jobs/performance/primer_single.sh 'census' 'svm_linear' 'standard' 1.0 7 1440 'short'
./jobs/performance/primer_single.sh 'census' 'svm_rbf' 'standard' 0.25 20 1440 'short'
./jobs/performance/primer_single.sh 'amazon' 'lr' 'standard' 1.0 20 1440 'short'
./jobs/performance/primer_single.sh 'amazon' 'svm_linear' 'standard' 1.0 20 1440 'short'
./jobs/performance/primer_single.sh 'amazon' 'svm_rbf' 'standard' 0.25 20 1440 'short'
./jobs/performance/primer_single.sh 'amazon' 'knn' 'standard' 0.25 10 1440 'short'

./jobs/performance/primer_single.sh 'churn' 'cb' 'categorical' 1.0 2 1440 'short'
./jobs/performance/primer_single.sh 'surgical' 'cb' 'categorical' 1.0 2 1440 'short'
./jobs/performance/primer_single.sh 'vaccine' 'cb' 'categorical' 1.0 2 1440 'short'
./jobs/performance/primer_single.sh 'amazon' 'cb' 'categorical' 1.0 7 1440 'short'
./jobs/performance/primer_single.sh 'bank_marketing' 'cb' 'categorical' 1.0 2 1440 'short'
./jobs/performance/primer_single.sh 'adult' 'cb' 'categorical' 1.0 2 1440 'short'
./jobs/performance/primer_single.sh 'census' 'cb' 'categorical' 1.0 7 1440 'short'
