sbatch jobs/cleaning/adult/1.sh
sbatch jobs/cleaning/adult/2.sh
sbatch jobs/cleaning/adult/3.sh
sbatch jobs/cleaning/adult/4.sh
sbatch jobs/cleaning/adult/5.sh
sbatch jobs/cleaning/adult/6.sh
sbatch jobs/cleaning/adult/7.sh
sbatch jobs/cleaning/adult/8.sh
sbatch jobs/cleaning/adult/9.sh
sbatch jobs/cleaning/adult/10.sh